spring:
  application:
    name: gateway
  threads:
    virtual:
      enabled: true

server:
  port: 7777

logging:
  level:
    org.springframework.cloud.gateway.server.mvc: TRACE
    org.springframework.web.client.RestClient: DEBUG
    org.springframework.web: DEBUG
    org.apache.hc.client5.http.wire: DEBUG
    # If you want headers too, add these optional loggers
    org.apache.hc.client5.http.headers: DEBUG
    org.apache.hc.client5.http: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: '*'

---
spring:
  config:
    activate:
      on-profile: observation
management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0
    propagation:
      type: w3c
  metrics:
    tags:
      application: gateway
    distribution:
      percentiles-histogram:
        http.server.requests: true
  opentelemetry:
    resource-attributes:
      "service.name": gateway
      "service.version": 1.0.0
      "deployment.environment": development
    tracing:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/traces
    logging:
      export:
        enabled: true
        otlp:
          endpoint: http://localhost:4318/v1/logs
          transport: http
  otlp:
    metrics:
      export:
        url: http://localhost:4318/v1/metrics
        step: 10s
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
